### ISSUE TITLE
SQL Exception Error while running CohortIncidenceModule

### ISSUE THREAD

**Issue by hmorgancooper** [ohdsi-studies/HowOften#14]
Hey :) I'm trying to get the HowOften study running and I'm erroring out during the CohortIncidenceModule section:
`Syntax error: Expected ")" but got keyword GROUPS at [59:5].`

I am using BigQuery SQL which has caused some issues in the past. I got this 'hint' in the errorReportSql.txt
--HINT DISTRIBUTE_ON_KEY(subject_id)

Also - I have a warning saying the renv is out of sync - apparently OhdsiRTools and Strategus are not available. When I run renv::restore() it's telling me the library is already synchronized with the lockfile though?

**Comment by chrisknoll** [comment]
This is fixed with CohortIncience v3.3.0, where we [optimized SQL and also fixed these keywords](https://github.com/OHDSI/CohortIncidence/commit/9c629b08982a9a29bcd7dbb4f82bd2728acf7553).

HowOften, however, uses renv to lock the modules to specific library versions, so it is currently using 3.2.0.  When we update HowOften, we will have the new version of the library and this will address it.  

As far as of the out of sync message, I am not sure exactly, but improvements on the Strategus versions have been made to address these types of messages, so when we have the next iteration of HowOften, we'll have that updated as well.

**Comment by hmorgancooper** [comment]
It ran all the way through! thanks for the help :) 

In case anyone else is running into a similar issue I changed the renv.lock file to use CohortIncidence v3.3.0 and I was using the develop branch of Strategus.
