### ISSUE TITLE
Error in analysis specifications

### ISSUE THREAD

**Issue by DrTTrousers** [ohdsi-studies/HowOften#7]
```
Error in (function (limitTo)  : 
  Assertion on 'limitTo' failed: Must be element of set {'','firstEver','earliestRemaining','latestRemaining','lastEver'}, but is 'all'.
Calls: execute ... <Anonymous> -> <Anonymous> -> makeAssertion -> mstop
```

The analysis specifications use an out of date assertion qualifier in their body. This impedes the progress

To remedy the value of limito needs to be deleted to an empty string.

**Comment by DrTTrousers** [comment]
Addendum:
This can be modified in all but the "overall" json directly in R, the overall file is too large to open in-editor

**Comment by chrisknoll** [comment]
Thank for the report.   You may be using an out-of-date analysis specification, can you make sure you have latest from master branch?  The module version should in the latest JSON should be reference the version of the cohort generator module that supports the 'all' option.

**Comment by chrisknoll** [comment]
I checked what was in azza.json (for example) and the module version is [0.2.1](https://github.com/ohdsi-studies/HowOften/blob/2158d2af12e3cead9c34920b214f90f6625486ce/howoften_azza.json#L37).  The renv.lock file is calling for 0.8.1 of CohortGenerator which does accept 'all' as a paramater.  So i'm not clear about how you are running this analysis, but somehow it's using an out-of-date module version.

**Comment by chrisknoll** [comment]
Ok, we've uncovered the issue:  While the CohortGeneratorModule contains an renv.lock file that specifies the correct version of 0.8.1 for CohortGenerator, the startup of the execution will use the SYSTEM installed CohortGenerator which in your case was 0.8.0 which raises this error due to an unsupported option.

Solution is to update your CohortGenerator package to 0.8.1.

This seems to be a special case of CohortGenerator, the other packages defined in the renv.lock will be used.

**Comment by chrisknoll** [comment]
This issue is described in Strategus: https://github.com/OHDSI/Strategus/issues/96

I've updated instructions that adds the step to ensure that you have CohortGenerator v0.8.1 installed.
